frontend:
  image: nginx:latest
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80

backend:
  image: my-backend:latest
  replicaCount: 2
  service:
    type: ClusterIP
    port: 8080

database:
  image: mysql:5.7
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    size: 1Gi
